#!/bin/sh

find -name "*.java" -exec javac -cp /usr/java/jdk1.7.0_25/jre/lib/plugin.jar {} +
jar cf JavaSocketBridge.jar *.class
/usr/java/jdk1.7.0_25/bin/keytool -genkey -keyalg rsa -alias yoba
/usr/java/jdk1.7.0_25/bin/keytool -certreq -alias yoba
# /usr/java/jdk1.7.0_25/bin/keytool -import -alias yoba -file yoba.cer
/usr/java/jdk1.7.0_25/bin/jarsigner JavaSocketBridge.jar yoba
